### ISSUE TITLE
Schema registry view doesn't load

### ISSUE THREAD

**Issue by chrisjbremner** [cloudhut/kowl#178]
I am running version 5.0.4 of the schema registry, and I noticed that when I point Kowl at this registry and go to the "Schema Registry" view, the REST API times out after 25s. My hunch as to what is going on, which I can't backup with logs because I'm not sure how to see the backend logs, is that the `/mode` endpoint wasn't added to the schema registry until 5.2.X, and so [this call fails](https://github.com/cloudhut/kowl/blob/9925900214ae7694cd10f2289cddb8adeb1b4f76/backend/pkg/owl/schema_overview.go#L52-L65). Would it make sense to have a `N/A` value for mode if the call to `/mode` returns a 404?

**Comment by weeco** [comment]
Hey @chrisjbremner ,
thak makes sense, thanks for submitting the issue. This could also be the cause of https://github.com/cloudhut/kowl/issues/163 . 

How does the http response look like? As you can see in the code we should get an appropriate error in that case.

**Comment by chrisjbremner** [comment]
The response is `{"error_code":404,"message":"HTTP 404 Not Found"}` and returns a 404. I agree that the code looks like it should show the error, but I also confirmed that both the calls to `/config` and `/subjects` take less than a second even though I have 1000+ topics, which seems to leave the failed call to `/mode` as the only reason for the REST timeout.

**Comment by chrisjbremner** [comment]
I should add that I am seeing this on `1.2.2` and `master`.

**Comment by weeco** [comment]
Hey @chrisjbremner ,
I took a look at the code and in case you were talking about the request that goes to `/api/schemas` the only possible HTTP response codes should be 503 or 200. If the request to /mode fails a 503 error is indeed expected (I can make that request optional though). Before doing so could you take a look at the logs printed in the Kowl backend and post them here?

**Comment by chrisjbremner** [comment]
Ah ok, the 404 was the response when I tried hitting `/mode` manually on my schema registry. When I hit `/api/schemas`, I get a 504 error, but it's after 1 min, rather than the 25s timeout. Is there a way I can get the backend logs? I did set the log level to `debug` in the `config.yaml` and here's what I got:
```
{"level":"info","ts":"2021-02-20T20:33:36.223Z","msg":"started Kowl","version":"master","git_sha":"c0912054711b113a54f05e2c5a010773defebe06","built":"2021-02-17T12:55:53Z"}
{"level":"info","ts":"2021-02-20T20:33:36.223Z","msg":"connecting to Kafka seed brokers, trying to fetch cluster metadata"}
{"level":"debug","ts":"2021-02-20T20:33:36.223Z","msg":"opening connection to broker","source":"kafka_client","addr":"xxxxx:yyyy","id":-2147483648}
{"level":"debug","ts":"2021-02-20T20:33:36.258Z","msg":"kafka connection succeeded","source":"kafka_client_hooks","host":"xxxxx","dial_duration":0.03489455}
{"level":"debug","ts":"2021-02-20T20:33:36.258Z","msg":"connection opened to broker","source":"kafka_client","addr":"xxxxx:yyyyy","id":-2147483648}
{"level":"debug","ts":"2021-02-20T20:33:36.258Z","msg":"issuing api versions request","source":"kafka_client","version":3}
{"level":"debug","ts":"2021-02-20T20:33:36.259Z","msg":"kafka does not know our ApiVersions version, downgrading to version 0 and retrying","source":"kafka_client"}
{"level":"debug","ts":"2021-02-20T20:33:36.259Z","msg":"issuing api versions request","source":"kafka_client","version":0}
{"level":"debug","ts":"2021-02-20T20:33:36.261Z","msg":"initialized api versions","source":"kafka_client","versions":[6,8,3,6,1,0,4,1,4,4,2,3,2,2,2,2,2,1,2,3,2,1,1,1,1,1,1,0,1,1,1,1,2,1,1,1,0,1,1,1,1,1,1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1]}
{"level":"debug","ts":"2021-02-20T20:33:36.261Z","msg":"connection initialized successfully","source":"kafka_client","addr":"xxxxx:yyyyy","id":-2147483648}
{"level":"debug","ts":"2021-02-20T20:33:36.278Z","msg":"opening connection to broker","source":"kafka_client","addr":"xxxxx:yyyyy","id":1}
{"level":"debug","ts":"2021-02-20T20:33:36.279Z","msg":"kafka connection succeeded","source":"kafka_client_hooks","host":"xxxxx","dial_duration":0.000774443}
{"level":"debug","ts":"2021-02-20T20:33:36.279Z","msg":"connection opened to broker","source":"kafka_client","addr":"xxxxx:yyyyy","id":1}
{"level":"debug","ts":"2021-02-20T20:33:36.279Z","msg":"issuing api versions request","source":"kafka_client","version":3}
{"level":"debug","ts":"2021-02-20T20:33:36.280Z","msg":"kafka does not know our ApiVersions version, downgrading to version 0 and retrying","source":"kafka_client"}
{"level":"debug","ts":"2021-02-20T20:33:36.280Z","msg":"issuing api versions request","source":"kafka_client","version":0}
{"level":"debug","ts":"2021-02-20T20:33:36.281Z","msg":"initialized api versions","source":"kafka_client","versions":[6,8,3,6,1,0,4,1,4,4,2,3,2,2,2,2,2,1,2,3,2,1,1,1,1,1,1,0,1,1,1,1,2,1,1,1,0,1,1,1,1,1,1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1]}
{"level":"debug","ts":"2021-02-20T20:33:36.281Z","msg":"connection initialized successfully","source":"kafka_client","addr":"xxxxx:yyyyy","id":1}
{"level":"info","ts":"2021-02-20T20:33:36.282Z","msg":"successfully connected to kafka cluster","advertised_broker_count":3,"topic_count":1735,"controller_id":1,"kafka_version":"v2.0"}
{"level":"info","ts":"2021-02-20T20:33:36.282Z","msg":"creating schema registry client and testing connectivity"}
{"level":"info","ts":"2021-02-20T20:33:36.360Z","msg":"successfully tested schema registry connectivity"}
{"level":"debug","ts":"2021-02-20T20:33:36.360Z","msg":"using compression for all http routes","level":4}
{"level":"info","ts":"2021-02-20T20:33:36.361Z","msg":"Server listening on address","address":"[::]:8080","port":8080}
{"level":"debug","ts":"2021-02-20T20:34:06.449Z","msg":"requested file not found","file":"/schema-registry"}
```

The last message is what I got when I clicked on the Schema Registry button in the navigation bar.

**Comment by chrisjbremner** [comment]
I've also confirmed I can retrieve a value from the `/schemas/subjects/{subject}/versions/{version}` endpoint, so it appears just to be the `/schemas` endpoint that hangs.

**Comment by weeco** [comment]
Okay I digged a little deeper and afterwards I just had a few more questions than before 😄 .

1. It should always log an error message when it returns a status code != 200 on that route.
2. A failed request to /mode or /config to the schema registry is already allowed and shouldn't cause an error.
3. The schema registry rest client has a timeout of 5s defined. So no request should take longer than 5s and all requests towards the schema registry will run concurrently.

My assumption is that the errgroup must get stuck somewhere (for forever) which would also explain why no error is logged at all. There's a function that is supposed to fetch the latest version and compatibility level for all subjects in the schema registry. It does that concurrently but since you have more than 1thousand topics - which possibly also are registered in your schema registry - this could overwhelm your schema registry and it might rate limit Kowl as well:

```go
// getSchemaSubjects fetches the latest version and the compatibility level for each subject from the schema registry.
// Requests are issued concurrently.
func (s *Service) getSchemaSubjects(subjects []string) []SchemaSubject {
```

I added a timeout of 25s for the errgroup to verify this theory. I think doing one request per topic doesn't scale very well and the schema registry is possibly not too happy about the amount of requests.

Could you try this tag `master-bb770098` and let me know if you see an error now after ~30s?

**Comment by chrisjbremner** [comment]
Thanks for pushing that change, I just tried it out but still experienced the same behavior as before. Frontend displays a REST timeout of 25s, and the call to `/schemas` returns a 504 after a minute. In the past I've used [`schema-registry-ui`](https://github.com/lensesio/schema-registry-ui) and found that it also can take longer than 30s to return all the schemas, and I believe it is also doing one request per topic. I agree that it's probably timing out on the `getSchemaSubjects` call and my theory about `/mode` is incorrect. Not knowing what the view looks like, is getting the details of every schema necessary for the overview page? I would assume that that would only be needed for the detail page and the overview page would just be a list of subjects.

**Comment by rikimaru0345** [comment]
@chrisjbremner 
Hi, I just merged the PR (weecos changes to the backend api, to prevent spamming the schema registry with requests) into master.
Can you try the latest build?  https://github.com/cloudhut/kowl/runs/1951354223?check_suite_focus=true#step:7:1

**Comment by chrisjbremner** [comment]
Hi @rikimaru0345 / @weeco, unfortunately when I tried out the latest build, I still experience the same timeout issue as described above. Is there any other additional information I can provide to help out? Here's my config for the schema registry:
```
kowl:
  config:
    kafka:
      brokers:
        - xxxx
      schemaRegistry:
        enabled: true
        urls: ['https://y.com:443']
    logger:
      level: debug
```

**Comment by weeco** [comment]
@chrisjbremner Do you mind joining our Discord so that we can take another look? It's quite hard to figure out that way because I'm not sure where it gets stuck and I can't reproduce this against any of our schema registries :/

**Comment by weeco** [comment]
Should be fixed by https://github.com/cloudhut/kowl/commit/df644a0a01847c7020e224652deac566d4de7e16
