### ISSUE TITLE
Fix display of values in Topic detail if schema has more than one type

### ISSUE THREAD

**Issue by chrisjbremner** [cloudhut/kowl#190]
I noticed that on the topic detail page, if I have a topic with the following Avro schema:
```
key1 -> [null, string]
key2 -> string
```

Then when a message is displayed in the topic detail page, it shows up as:
```json
{
  "key1": {
    "string": "value1"
  },
  "key2": "value2"
}
```

Ideally, it would display as:
```json
{
  "key1": "value1",
  "key2": "value2"
}
```

I inspected the `messages` websocket and confirmed that the message that was displayed came from the backend. I suspect what is returned is simply what Kafka stores internally, but I was wondering if it's possible to strip out these types when deserializing from an Avro schema?

**Comment by weeco** [comment]
@chrisjbremner I just pushed a commit that potentially fixes this. Could you give it a spin? If this hasn't fixed it I'm afraid I can't do much about it and in that case it might make sense to submit an issue in the repo of the go-avro client maintained by Linkedin.

**Comment by chrisjbremner** [comment]
Just tried out `kowl:master-06fbeced` but looks like the issue still persists. Thanks for giving it a shot, I will submit to `go-avro`

**Comment by chrisjbremner** [comment]
Oof, `go-avro` doesn't look like its actively maintained anymore

**Comment by chrisjbremner** [comment]
Looks like someone already made one (https://github.com/linkedin/goavro/issues/167) there's https://github.com/linkedin/goavro/pull/201 that fixes this, but it's been open for a while and hasn't been merged
